In [1]:
# Name: Vinayak Sindagi
# Reg No: 24-27-30
# Programme: M.Tech. Data Science
# Assignment Number: 2

In [2]:
import numpy as np

### Question 1

In [4]:
# Part a

var1 = np.arange(31)
print('var1:\n ',var1)
print('Shape of var1 is :',var1.shape)

var1:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape of var1 is : (31,)


In [5]:
# Part b

var2 = var1.reshape(31,1) # Since 31 elements are there shape of (5,6) or (6,5) is not possible.
print('var2:\n ',var2)
print('Shape of var2 is :',var2.shape)

var2:
  [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
Shape of var2 is : (31, 1)


In [6]:
# Part c

var3 = var2.reshape(1,31,1)
print('var3:\n ',var3)
print('Shape of var3 is :',var3.shape)

var3:
  [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]
Shape of var3 is : (1, 31, 1)


In [7]:
# Part d

var2[1,0] = -1      #Assigning first value in the second row of var2 to -1
print('var2 after modification:\n',var2)
print('var1 after modification:\n',var1)
print('var3 after modification:\n',var3)

# We can clearley see that:
# Both var1 and var3 is changed because reshape doesn't returns copy rather it returns view (in most of the cases).

var2 after modification:
 [[ 0]
 [-1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]
var1 after modification:
 [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
var3 after modification:
 [[[ 0]
  [-1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


In [8]:
#part e

# (i) Sum var3 over its second dimension and printing the result.
sum_over_sec = np.sum(var3,axis=1)    
print('Sum of var3 over its second dimension\n',sum_over_sec)

# (ii) Sum var3 over its third dimension and print the result.
sum_over_thr = np.sum(var3,axis=2)   
print('\nSum of var3 over its third dimension\n',sum_over_thr)

# (iii) Sum var3 over both first and third dimensions
sum_over_first_and_third = np.sum(var3, axis=(0, 2))
print("\nSum of var3 over both first and third dimensions:\n", sum_over_first_and_third)

# If axis=0, it sums over the first dimension (depth).
# If axis=1, it sums over the second dimension (rows).
# If axis=2, it sums over the third dimension (columns).

Sum of var3 over its second dimension
 [[463]]

Sum of var3 over its third dimension
 [[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]

Sum of var3 over both first and third dimensions:
 [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [9]:
#part f

# (i) Slice out the second row of var2 and print it.
sec_row_var2 = var2[1,:]
print('Second row of Var2 is:\n',sec_row_var2)

# (ii) Slice out the last column of var2 using the -1 notation and print it.
lst_col_var2 = var2[:,-1]
print('\nLast column of var2 is:\n',lst_col_var2)

# (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
# since it is not possible,  we will create the matrix of size 6x5  and name it as var4

var4 = np.arange(1,31).reshape(5,6)
print('\nVar4 is:\n',var4)
top_rgt_matrix = var4[:2,4:]
print('\nTop right 2 × 2 submatrix of var2 is:\n',top_rgt_matrix)

Second row of Var2 is:
 [-1]

Last column of var2 is:
 [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]

Var4 is:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Top right 2 × 2 submatrix of var2 is:
 [[ 5  6]
 [11 12]]


### Question 2

In [11]:
#Part a

# 

arr = np.arange(10)
print('Vector Before Broadcadcasting: ',arr)

arr1 = arr+1
print('Vector after Broadcadcasting: ',arr1)
arr1.shape

Vector Before Broadcadcasting:  [0 1 2 3 4 5 6 7 8 9]
Vector after Broadcadcasting:  [ 1  2  3  4  5  6  7  8  9 10]


(10,)

In [12]:
# part b

# creating a 10x10 matrix A in which Aij = i + j.

vector = arr1.reshape(10,1)
matrix = vector+arr1
print('matrix A:\n',matrix)

matrix A:
 [[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


In [13]:
# part c

import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) ) # Creating a dummy dataset of random numbers of 50 rows and 5 columns
data

array([[ 1.09567059,  0.61532612,  1.64480102,  0.52365002,  0.67823808],
       [ 0.5720722 ,  1.03580241, 16.95197698,  2.14028392,  0.92290227],
       [ 0.13730182,  0.65115957,  2.7436633 ,  2.83905584,  0.47542104],
       [ 0.68772454,  2.39544225,  1.00406316,  0.91925919,  0.91726668],
       [ 0.72794099,  0.2967898 ,  0.93517477,  0.48635787,  1.89285312],
       [ 1.10644302,  0.14468773,  1.25330527,  0.44283177,  0.41464095],
       [ 1.7800284 ,  2.84736979,  0.38467995,  1.36704178,  0.34094949],
       [ 2.61624748,  3.4308155 ,  0.19983299,  0.38517491,  0.0703507 ],
       [ 1.42429955,  0.63419086,  1.23649678,  0.48944363,  0.40377184],
       [ 2.12548523,  2.11834884,  3.53315769,  4.99500664,  2.32103121],
       [ 3.31907531,  1.14598496,  0.76533178,  0.13101549,  0.4676758 ],
       [ 2.79417503,  2.74877986,  2.06258973,  0.92859811,  2.38498831],
       [ 0.17532309,  2.21232949,  0.11516023,  0.35834783,  2.64192854],
       [ 1.08985756,  0.44762929,  0.2

In [14]:
#part e

# Calculating mean and standard deviation of each column

mean = np.mean(data,axis = 0)
std = np.std(data,axis = 0)
print('Mean of each column:',mean)
print('Standard deviation of each column: ',std)

Mean of each column: [1.68659879 1.58367056 1.60378721 1.20422147 1.36515406]
Standard deviation of each column:  [1.84544131 1.90626284 2.83931169 1.51774477 2.00343444]


In [15]:
# part f
# Standardizing the data and finding the mean and standard deviation

normalized = (data-mean)/std
print('Normalized data =\n',normalized)

mean_nor = np.mean(normalized,axis = 0)
std_nor = np.std(normalized,axis = 0)

print('\nMean of each column:',mean_nor)
print('\nStandard deviation of each column: ',std_nor)

Normalized data =
 [[-0.3202097  -0.50798055  0.01444499 -0.44840968 -0.34286921]
 [-0.603935   -0.28740431  5.40560229  0.61674563 -0.22074682]
 [-0.83952655 -0.4891828   0.40146212  1.0771471  -0.44410389]
 [-0.54126579  0.42584458 -0.21122163 -0.18775376 -0.22355979]
 [-0.51947347 -0.67508044 -0.23548399 -0.47298045  0.26339722]
 [-0.31437238 -0.75487115 -0.12343905 -0.50165859 -0.47444183]
 [ 0.05062724  0.66291972 -0.42936718  0.10727779 -0.5112244 ]
 [ 0.50375413  0.96898754 -0.49446992 -0.5396471  -0.64629186]
 [-0.14213362 -0.49808436 -0.12935897 -0.47094732 -0.47986707]
 [ 0.23782194  0.28048508  0.6795205   2.49764338  0.47711926]
 [ 0.88459953 -0.22960402 -0.29530235 -0.7071057  -0.44796987]
 [ 0.60016877  0.61120077  0.16158935 -0.1816006   0.50904299]
 [-0.81892374  0.32978607 -0.5242915  -0.55732272  0.63729287]
 [-0.32335964 -0.59595206 -0.49234741 -0.37348465 -0.01566882]
 [ 0.32653273 -0.01834402 -0.021174   -0.51817316 -0.62468671]
 [-0.80588671 -0.36789508  0.0464385

### Question 3

In [17]:
# part a

# creating a Vandermonde matrix for N=3

def vandermonde (N):
    vec = np.arange (N) +1
    vec1 = np.arange(N)
    vec = vec.reshape(N,1)
    Matrix = (pow(vec,vec1))
    print(Matrix)
    return Matrix
   
n = 12
vander = n     #storing N=12 in a variable named 'vander'.
print('Vandermonde matrix is:')
Matrix_1 = vandermonde(vander)

Vandermonde matrix is:
[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       11

In [18]:
# part b

x = np.ones(12)
b = np.dot(Matrix_1,x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [19]:
# part c

# Solving the linear system the naïve way

Matrix_1_inv = np.linalg.inv(Matrix_1)
Sol = np.dot(Matrix_1_inv,b)
print(Sol)

# The result is almost ones(12) with slight variation maybe due to floating points instability while inversing Vector

[0.99620819 1.00462723 0.99909973 1.00006104 0.99999666 1.00000048
 0.99999995 1.         1.         1.         1.         1.        ]


In [20]:
# d solve using numpy

Sol_inbuilt = np.linalg.solve(Matrix_1,b)

print(Sol_inbuilt)

[0.99998827 1.00002951 0.99997139 1.00001427 0.99999595 1.00000068
 0.99999993 1.         1.         1.         1.         1.        ]


In [21]:
# The solution using .solve() seems more accurate but let's verify that using some statistics 

Diff_solve = x - Sol
Diff_solve_inbuilt = x - Sol_inbuilt
print(np.std(Diff_solve) , np.std(Diff_solve_inbuilt) )
# clearly the inbuilt function method's solution is more closer to ones(12)

0.0017465029209462444 1.3062999784531137e-05


In [22]:
# https://github.com/vinayak-sindagi/DSTT/tree/main/Vinayak%20Sindagi_24-27-30